### ISSUE TITLE
seems not work in my environment

### ISSUE THREAD

**Issue by ChenLingPeng** [juliens/ktls-bpf_redirect-example#1]
hi, I'm running this code in my ubuntu system and something is wrong.
```
# uname -r
5.15.0-84-generic
```
<img width="620" alt="image" src="https://github.com/juliens/ktls-bpf_redirect-example/assets/1817942/d1b8816f-f0d1-49c6-ba43-bb70325d32cc">

as shown above, when sending data from openssl client, the server(nc) will receive some binary bytes with the right raw data.

I added `bpf_printk` both in `_prog_parser` and `_prog_verdict` and found that `_prog_parser` only triggered when nc send data back to openssl, sending data from openssl side will not trigger `_prog_parser`. Is it expected or is there something wrong?

**Comment by juliens** [comment]
Hello,
The actual goal of this example was to highlight an issue in the kernel. I attempted to resolve it and submitted a change request. However, due to extensive code modifications, it is now outdated.

**Comment by ChenLingPeng** [comment]
hi julien,
thanks for your reply. so the repo bpf-exp-rp has the same issue, right?
do you know why `_prog_parser` is not executed when sending data from openssl client?

**Comment by juliens** [comment]
Yes, the issue persists with bpf-exp-rp, and the reason for its non-execution remains unclear. This problem is tied to the fact that `_prog_parser` and `ktls` both utilize the same mechanism, resulting in a conflict.

**Comment by ChenLingPeng** [comment]
thanks for pointing this out

**Comment by soulxu** [comment]
> Hello, The actual goal of this example was to highlight an issue in the kernel. I attempted to resolve it and submitted a change request. However, due to extensive code modifications, it is now outdated.

@juliens do you have a link or mail list for discussion this issue in the kernel side, I saw this issue also. I want to track when this can be fixed.

**Comment by juliens** [comment]
See the thread on the mailing list here : https://lore.kernel.org/bpf/62bbf87f16223_2181420853@john.notmuch/

**Comment by soulxu** [comment]
> See the thread on the mailing list here : https://lore.kernel.org/bpf/62bbf87f16223_2181420853@john.notmuch/

@juliens thanks a lot! It seems the last reply is a year ago, it seems no hope to be fixed, right?

**Comment by juliens** [comment]
You're right, it's been a while since nothing happen on this thread.
To be honest, I'm not familiar enough with the kernel source code to fix it. Nevertheless, I maintain hope that resolving a different bug might indirectly lead to the resolution of this one.

**Comment by soulxu** [comment]
> You're right, it's been a while since nothing happen on this thread. To be honest, I'm not familiar enough with the kernel source code to fix it. Nevertheless, I maintain hope that resolving a different bug might indirectly lead to the resolution of this one.

got it, thanks for helping me understand the status!

**Comment by soulxu** [comment]
> > You're right, it's been a while since nothing happen on this thread. To be honest, I'm not familiar enough with the kernel source code to fix it. Nevertheless, I maintain hope that resolving a different bug might indirectly lead to the resolution of this one.
> 
> got it, thanks for helping me understand the status!

@juliens just want you know, I tested in the 6.x version kernel, it works now :)

**Comment by juliens** [comment]
I'm not sure it's completly fixed.

I tried with 6.7.0
```
Linux juliens 6.7.0 #1-NixOS SMP PREEMPT_DYNAMIC Sun Jan  7 20:18:38 UTC 2024 x86_64 GNU/Linux
```

When I send:
```
read R BLOCK
TEST
TEST
TEST
```

I receive:
```
❯ nc -l 0.0.0.0 8080
TEST
xTEST
tobject.serialr_202TEST
06_p1%22%2C1%2Cn
```

**Comment by ChenLingPeng** [comment]
it works in my environment
`Linux ubuntu2304.localdomain 6.2.0-33-generic #33-Ubuntu SMP PREEMPT_DYNAMIC Tue Sep  5 14:49:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

But when sending a large message, the server seems not to receive all of them
